Repository packit/requre, pull requests merged in 2025-02, with the labels that each got.

#296 Support streamable raw responses
  requre/helpers/requests_response.py
  tests/testbase.py
Labels: mergeit

#298 Fix getting decoded response data
  requre/helpers/requests_response.py
Labels: mergeit

#299 Purge Pagure and Copr secrets
  .pre-commit-hooks.yaml
Labels: mergeit

#297 Feat/httpx
  Makefile
  pyproject.toml
  requre/helpers/__init__.py
  requre/helpers/httpx_response.py
  requre/objects.py
  tests/test_httpx.py
Labels: mergeit

#301 Test and verify with tmt and TF
  .fmf/version
  .packit.yaml
  .pre-commit-config.yaml
  ci.fmf
  plans/full.fmf
  plans/main.fmf
  plans/ogr-integration.fmf
  plans/packit-integration.fmf
  plans/rpmlint.fmf
  plans/smoke.fmf
  tests/full.fmf
  tests/smoke.fmf
  tests/smoke.sh
Labels: testing, mergeit

#300 chore: release 0.9.0
  CHANGELOG.md
  fedora/python-requre.spec
Labels: mergeit, release
